name: SpaceSwitcher
options:
  bundleIdPrefix: com.spaceswitcher
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.2.0"
  LaunchAtLogin:
    url: https://github.com/sindresorhus/LaunchAtLogin-Modern
    from: "1.1.0"

targets:
  SpaceSwitcher:
    type: application
    platform: macOS
    sources:
      - path: SpaceSwitcher
        excludes:
          - "Resources/Info.plist"
    info:
      path: SpaceSwitcher/Resources/Info.plist
      properties:
        LSUIElement: true
        CFBundleDisplayName: SpaceSwitcher
        CFBundleName: SpaceSwitcher
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
    entitlements:
      path: SpaceSwitcher/SpaceSwitcher.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.spaceswitcher.SpaceSwitcher
        PRODUCT_NAME: SpaceSwitcher
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        CODE_SIGN_ENTITLEMENTS: SpaceSwitcher/SpaceSwitcher.entitlements
        INFOPLIST_FILE: SpaceSwitcher/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_APP_SANDBOX: NO
        CODE_SIGN_IDENTITY: "-"
        DEVELOPMENT_TEAM: ""
        SWIFT_STRICT_CONCURRENCY: complete
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
    dependencies:
      - package: KeyboardShortcuts
      - package: LaunchAtLogin
